apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss.fullname" . }}-app
spec:
  selector:
    app.kubernetes.io/component: app
    {{- include "ttrss.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
