apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ttrss.fullname" . }}-config
data:
  APP_WEB_ROOT: "/var/www/html/tt-rss"
  APP_BASE: ""
  TTRSS_SELF_URL_PATH: {{ .Values.ingress.host | quote }}
  APP_UPSTREAM: {{ include "ttrss.fullname" . }}-app.{{ .Release.Namespace }}.svc.cluster.local
  RESOLVER: "kube-dns.kube-system.svc.cluster.local"
  TTRSS_DB_PORT: "5432"
  TTRSS_DB_HOST: {{ include "ttrss.fullname" . }}-db.{{ .Release.Namespace }}.svc.cluster.local
  TTRSS_DB_NAME: "ttrss"
