apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ttrss.fullname" . }}-pvc-db
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ttrss.fullname" . }}-pvc-app
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
