apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ttrss.fullname" . }}-secrets
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
type: Opaque
data:
  TTRSS_DB_USER: YWRtaW4=
  TTRSS_DB_PASS: {{ randAlphaNum 16 | b64enc | quote }}
  ADMIN_USER_PASS: {{ randAlphaNum 16 | b64enc | quote }}
