apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ttrss.fullname" . }}-secrets
  labels:
    {{- include "ttrss.labels" . | nindent 4 }}
type: Opaque
data:
  TTRSS_DB_USER: {{ .Values.db.username | b64enc | quote }}
  TTRSS_DB_PASS: {{ .Values.db.password | b64enc | quote }}
  ADMIN_USER_PASS: {{ .Values.admin.password | b64enc | quote }}
