apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttrss.fullname" . }}-web
spec:
  selector:
    app.kubernetes.io/component: web
    {{- include "ttrss.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
